// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products";
  };
  "./layouts/Layout.tsx": {
    id: "layouts/Layout";
    page: "/" | "/products";
  };
  "./routes/Landing.tsx": {
    id: "routes/Landing";
    page: "/";
  };
  "./routes/Products.tsx": {
    id: "routes/Products";
    page: "/products";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/Layout": typeof import("./src/./layouts/Layout.tsx");
  "routes/Landing": typeof import("./src/./routes/Landing.tsx");
  "routes/Products": typeof import("./src/./routes/Products.tsx");
};